server {
    listen 80;
<<<<<<< HEAD

    location / {
        root /usr/share/nginx/html;
        index index.html;
=======
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
>>>>>>> a4b2f72 (k8s 포트포워딩 배포 지원)
        try_files $uri $uri/ /index.html;
    }

    location /scan {
<<<<<<< HEAD
        proxy_pass http://terraform-backend-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
=======
        proxy_pass http://terraform-scanner-backend-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        client_max_body_size 50M;
>>>>>>> a4b2f72 (k8s 포트포워딩 배포 지원)
    }
}